const words = {
    "tajik": {
        "emotions": [
            {"word": "хурсандӣ", "translation": "радость"},
            {"word": "ғамгинӣ", "translation": "печаль"},
            {"word": "тарс", "translation": "страх"},
            {"word": "хашм", "translation": "гнев"},
            {"word": "ҳаяҷон", "translation": "волнение"},
            {"word": "маҳзунӣ", "translation": "огорчение"},
            {"word": "ғазаб", "translation": "ярость"},
            {"word": "шодӣ", "translation": "счастье"},
            {"word": "муҳаббат", "translation": "любовь"},
            {"word": "кӯҳнарин", "translation": "усталость"},
            {"word": "ғурур", "translation": "гордость"},
            {"word": "ноумедӣ", "translation": "разочарование"},
            {"word": "умед", "translation": "надежда"},
            {"word": "иродат", "translation": "воля"},
            {"word": "сабр", "translation": "терпение"}
        ],
        "objects": [
            {"word": "китоб", "translation": "книга"},
            {"word": "мошин", "translation": "машина"},
            {"word": "миз", "translation": "стол"},
            {"word": "курси", "translation": "стул"},
            {"word": "рақам", "translation": "телефон"},
            {"word": "хона", "translation": "дом"},
            {"word": "коғаз", "translation": "бумага"},
            {"word": "қалам", "translation": "ручка"},
            {"word": "компютер", "translation": "компьютер"},
            {"word": "лаҳза", "translation": "время"},
            {"word": "чангал", "translation": "лес"},
            {"word": "шаҳр", "translation": "город"},
            {"word": "қуттӣ", "translation": "коробка"},
            {"word": "дарвоза", "translation": "ворота"},
            {"word": "гул", "translation": "цветок"}
        ],
        "nature": [
            {"word": "об", "translation": "вода"},
            {"word": "гул", "translation": "цветок"},
            {"word": "барг", "translation": "лист"},
            {"word": "хок", "translation": "земля"},
            {"word": "осмон", "translation": "небо"},
            {"word": "ситора", "translation": "звезда"},
            {"word": "моҳ", "translation": "луна"},
            {"word": "шамол", "translation": "ветер"},
            {"word": "борон", "translation": "дождь"},
            {"word": "барф", "translation": "снег"},
            {"word": "чароғ", "translation": "свет"},
            {"word": "соя", "translation": "тень"},
            {"word": "кӯҳ", "translation": "гора"},
            {"word": "дарё", "translation": "река"},
            {"word": "баҳор", "translation": "весна"}
        ],
        "technology": [
            {"word": "компютер", "translation": "компьютер"},
            {"word": "телефон", "translation": "телефон"},
            {"word": "мошин", "translation": "машина"},
            {"word": "принтер", "translation": "принтер"},
            {"word": "плеер", "translation": "плеер"},
            {"word": "телевизор", "translation": "телевизор"},
            {"word": "камера", "translation": "камера"},
            {"word": "лампа", "translation": "лампа"},
            {"word": "акумулятор", "translation": "аккумулятор"},
            {"word": "радио", "translation": "радио"},
            {"word": "модем", "translation": "модем"},
            {"word": "монитор", "translation": "монитор"},
            {"word": "ноутбук", "translation": "ноутбук"},
            {"word": "проектор", "translation": "проектор"},
            {"word": "микрофон", "translation": "микрофон"}
        ]
    },
    "uzbek": {
        "emotions": [
            {"word": "xursandlik", "translation": "радость"},
            {"word": "qayg'u", "translation": "печаль"},
            {"word": "qo'rquv", "translation": "страх"},
            {"word": "g'azab", "translation": "гнев"},
            {"word": "hayajon", "translation": "волнение"},
            {"word": "xafalik", "translation": "огорчение"},
            {"word": "achchiq", "translation": "ярость"},
            {"word": "shodlik", "translation": "счастье"},
            {"word": "sevgi", "translation": "любовь"},
            {"word": "charchoq", "translation": "усталость"},
            {"word": "faxr", "translation": "гордость"},
            {"word": "umidsizlik", "translation": "разочарование"},
            {"word": "umid", "translation": "надежда"},
            {"word": "iroda", "translation": "воля"},
            {"word": "sabir", "translation": "терпение"}
        ],
        "objects": [
            {"word": "kitob", "translation": "книга"},
            {"word": "mashina", "translation": "машина"},
            {"word": "stol", "translation": "стол"},
            {"word": "stul", "translation": "стул"},
            {"word": "telefon", "translation": "телефон"},
            {"word": "uy", "translation": "дом"},
            {"word": "qog'oz", "translation": "бумага"},
            {"word": "ruchka", "translation": "ручка"},
            {"word": "kompyuter", "translation": "компьютер"},
            {"word": "vaqt", "translation": "время"},
            {"word": "o'rmon", "translation": "лес"},
            {"word": "shahar", "translation": "город"},
            {"word": "quti", "translation": "коробка"},
            {"word": "darvoza", "translation": "ворота"},
            {"word": "gul", "translation": "цветок"}
        ],
        "nature": [
            {"word": "suv", "translation": "вода"},
            {"word": "gul", "translation": "цветок"},
            {"word": "barg", "translation": "лист"},
            {"word": "yer", "translation": "земля"},
            {"word": "osmon", "translation": "небо"},
            {"word": "yulduz", "translation": "звезда"},
            {"word": "oy", "translation": "луна"},
            {"word": "shamol", "translation": "ветер"},
            {"word": "yomg'ir", "translation": "дождь"},
            {"word": "qor", "translation": "снег"},
            {"word": "yorug'lik", "translation": "свет"},
            {"word": "soya", "translation": "тень"},
            {"word": "tog'", "translation": "гора"},
            {"word": "daryo", "translation": "река"},
            {"word": "bahor", "translation": "весна"}
        ],
        "technology": [
            {"word": "kompyuter", "translation": "компьютер"},
            {"word": "telefon", "translation": "телефон"},
            {"word": "mashina", "translation": "машина"},
            {"word": "printer", "translation": "принтер"},
            {"word": "pleyer", "translation": "плеер"},
            {"word": "televizor", "translation": "телевизор"},
            {"word": "kamera", "translation": "камера"},
            {"word": "lampa", "translation": "лампа"},
            {"word": "batareya", "translation": "аккумулятор"},
            {"word": "radio", "translation": "радио"},
            {"word": "modem", "translation": "модем"},
            {"word": "monitor", "translation": "монитор"},
            {"word": "noutbuk", "translation": "ноутбук"},
            {"word": "proyektor", "translation": "проектор"},
            {"word": "mikrofon", "translation": "микрофон"}
        ]
    },
    "kyrgyz": {
        "emotions": [
            {"word": "кубаныч", "translation": "радость"},
            {"word": "кайгы", "translation": "печаль"},
            {"word": "коркунуч", "translation": "страх"},
            {"word": "ачуулануу", "translation": "гнев"},
            {"word": "толкундануу", "translation": "волнение"},
            {"word": "өкүнүч", "translation": "огорчение"},
            {"word": "ачуу", "translation": "ярость"},
            {"word": "бактылуулук", "translation": "счастье"},
            {"word": "сүйүү", "translation": "любовь"},
            {"word": "чарчоо", "translation": "усталость"},
            {"word": "сыймыктануу", "translation": "гордость"},
            {"word": "үмүтсүздүк", "translation": "разочарование"},
            {"word": "үмүт", "translation": "надежда"},
            {"word": "эрк", "translation": "воля"},
            {"word": "сабырдуулук", "translation": "терпение"}
        ],
        "objects": [
            {"word": "китеп", "translation": "книга"},
            {"word": "машина", "translation": "машина"},
            {"word": "стол", "translation": "стол"},
            {"word": "отургуч", "translation": "стул"},
            {"word": "телефон", "translation": "телефон"},
            {"word": "үй", "translation": "дом"},
            {"word": "кагаз", "translation": "бумага"},
            {"word": "калем", "translation": "ручка"},
            {"word": "компьютер", "translation": "компьютер"},
            {"word": "убакыт", "translation": "время"},
            {"word": "токой", "translation": "лес"},
            {"word": "шаар", "translation": "город"},
            {"word": "куту", "translation": "коробка"},
            {"word": "дарбаза", "translation": "ворота"},
            {"word": "гүл", "translation": "цветок"}
        ],
        "nature": [
            {"word": "суу", "translation": "вода"},
            {"word": "гүл", "translation": "цветок"},
            {"word": "жалбырак", "translation": "лист"},
            {"word": "жер", "translation": "земля"},
            {"word": "асман", "translation": "небо"},
            {"word": "жылдыз", "translation": "звезда"},
            {"word": "ай", "translation": "луна"},
            {"word": "шамал", "translation": "ветер"},
            {"word": "жамгыр", "translation": "дождь"},
            {"word": "кар", "translation": "снег"},
            {"word": "жарык", "translation": "свет"},
            {"word": "көч", "translation": "тень"},
            {"word": "тоо", "translation": "гора"},
            {"word": "арык", "translation": "река"},
            {"word": "жаз", "translation": "весна"}
        ],
        "technology": [
            {"word": "компьютер", "translation": "компьютер"},
            {"word": "телефон", "translation": "телефон"},
            {"word": "машина", "translation": "машина"},
            {"word": "принтер", "translation": "принтер"},
            {"word": "плеер", "translation": "плеер"},
            {"word": "телевизор", "translation": "телевизор"},
            {"word": "камера", "translation": "камера"},
            {"word": "лампа", "translation": "лампа"},
            {"word": "батарея", "translation": "аккумулятор"},
            {"word": "радио", "translation": "радио"},
            {"word": "модем", "translation": "модем"},
            {"word": "монитор", "translation": "монитор"},
            {"word": "ноутбук", "translation": "ноутбук"},
            {"word": "проектор", "translation": "проектор"},
            {"word": "микрофон", "translation": "микрофон"}
        ]
    },
    "kazakh": {
        "emotions": [
            {"word": "қуаныш", "translation": "радость"},
            {"word": "қайғы", "translation": "печаль"},
            {"word": "қорқыныш", "translation": "страх"},
            {"word": "ашу", "translation": "гнев"},
            {"word": "қобалжу", "translation": "волнение"},
            {"word": "өкініш", "translation": "огорчение"},
            {"word": "ашу-ыза", "translation": "ярость"},
            {"word": "бақыт", "translation": "счастье"},
            {"word": "махаббат", "translation": "любовь"},
            {"word": "шаршау", "translation": "усталость"},
            {"word": "мақтаныш", "translation": "гордость"},
            {"word": "үмітсіздік", "translation": "разочарование"},
            {"word": "үміт", "translation": "надежда"},
            {"word": "ерік", "translation": "воля"},
            {"word": "сабыр", "translation": "терпение"}
        ],
        "objects": [
            {"word": "кітап", "translation": "книга"},
            {"word": "көлік", "translation": "машина"},
            {"word": "үстел", "translation": "стол"},
            {"word": "орындық", "translation": "стул"},
            {"word": "телефон", "translation": "телефон"},
            {"word": "үй", "translation": "дом"},
            {"word": "қағаз", "translation": "бумага"},
            {"word": "қалам", "translation": "ручка"},
            {"word": "компьютер", "translation": "компьютер"},
            {"word": "уақыт", "translation": "время"},
            {"word": "орман", "translation": "лес"},
            {"word": "қала", "translation": "город"},
            {"word": "қорап", "translation": "коробка"},
            {"word": "қақпа", "translation": "ворота"},
            {"word": "гүл", "translation": "цветок"}
        ],
        "nature": [
            {"word": "су", "translation": "вода"},
            {"word": "гүл", "translation": "цветок"},
            {"word": "жапырақ", "translation": "лист"},
            {"word": "жер", "translation": "земля"},
            {"word": "аспан", "translation": "небо"},
            {"word": "жұлдыз", "translation": "звезда"},
            {"word": "ай", "translation": "луна"},
            {"word": "жел", "translation": "ветер"},
            {"word": "жаңбыр", "translation": "дождь"},
            {"word": "қар", "translation": "снег"},
            {"word": "жарық", "translation": "свет"},
            {"word": "көлеңке", "translation": "тень"},
            {"word": "тау", "translation": "гора"},
            {"word": "өзен", "translation": "река"},
            {"word": "көктем", "translation": "весна"}
        ],
        "technology": [
            {"word": "компьютер", "translation": "компьютер"},
            {"word": "телефон", "translation": "телефон"},
            {"word": "көлік", "translation": "машина"},
            {"word": "принтер", "translation": "принтер"},
            {"word": "плеер", "translation": "плеер"},
            {"word": "телевизор", "translation": "телевизор"},
            {"word": "камера", "translation": "камера"},
            {"word": "лампа", "translation": "лампа"},
            {"word": "батарея", "translation": "аккумулятор"},
            {"word": "радио", "translation": "радио"},
            {"word": "модем", "translation": "модем"},
            {"word": "монитор", "translation": "монитор"},
            {"word": "ноутбук", "translation": "ноутбук"},
            {"word": "проектор", "translation": "проектор"},
            {"word": "микрофон", "translation": "микрофон"}
        ]
    }
};
